name: Build Extension

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Make build script executable
      run: chmod +x build.sh
      
    - name: Run build script
      run: ./build.sh -v 2.2.2
      
    - name: Upload Chrome extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: find-chrome-extension
        path: .build/find-chrome.zip
       
    - name: Generate attestation for Chrome extension
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: .build/find-chrome.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v2.2.2
        target_commitish: ${{ github.ref_name }}
        generate_release_notes: true
        draft: true
        files: |
          .build/find-chrome.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}